#!/usr/bin/env bash

# Set root directory
root_dir=$(dirname "${0}")

# Compose the 'run' command
run_command="${root_dir}/solutions/${1}/run ${2}"

# Read the output for the specified language/solution pair
echo "$(${run_command})"
