#!/usr/bin/env bash

# Set root directory
root_dir=$(readlink -f "${0}" | xargs realpath | xargs dirname)

# Compose a padded solution number
pe_number="${2}"
while [ ${#pe_number} -lt 3 ]
do
    pe_number="0${pe_number}"
done

# Compose the 'run' command
run_command="${root_dir}/solutions/${1}/run ${pe_number}"

# Read the output for the specified language/solution pair
echo "$(${run_command})" | awk 'NF'
